[phases.setup]
nixPkgs = ["php83", "php83Extensions.mbstring", "php83Extensions.pdo", "php83Extensions.pdo_mysql"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs",
    "npm install --production=false",
    "npm run build",
    "rm -rf node_modules"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
