[phases.setup]
nixPkgs = ["php83", "php83Extensions.mbstring", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.tokenizer", "php83Extensions.xml", "php83Extensions.ctype", "php83Extensions.fileinfo", "php83Extensions.curl"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-interaction",
    "npm install --production=false",
    "npm run build",
    "rm -rf node_modules"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
